# Generated by Django 4.2.23 on 2025-07-08 18:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chapters', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Executive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('photo', models.ImageField(upload_to='executives/')),
                ('role', models.CharField(max_length=100)),
                ('bio', models.TextField(blank=True)),
                ('level', models.CharField(choices=[('national', 'National'), ('chapter', 'Chapter')], max_length=10)),
                ('chapter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='chapters.chapter')),
            ],
        ),
    ]
