# Generated by Django 4.2.23 on 2025-07-08 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chapters', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='chapter_pics/'),
        ),
    ]
